USE GD1C2020;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Estadia') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Estadia;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Pasaje') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Pasaje;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Nota_De_Venta') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Nota_De_Venta;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Compra') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Compra;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Empresa') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Empresa;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Ruta_Aerea') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Ruta_Aerea;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Ciudad') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Ciudad;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Vuelo') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Vuelo;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Habitacion') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Habitacion;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Hotel') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Hotel;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Cliente') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Cliente;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Sucursal') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Sucursal;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Butaca') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Butaca;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Avion') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Avion;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Tipo_Butaca') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Tipo_Butaca;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Tipo_Habitacion') IS NOT NULL
	DROP TABLE SELECT_QUANTUM_LIBRARY.Tipo_Habitacion;

IF OBJECT_ID ('SELECT_QUANTUM_LIBRARY.Migracion') IS NOT NULL
	DROP PROCEDURE SELECT_QUANTUM_LIBRARY.Migracion;

DROP SCHEMA SELECT_QUANTUM_LIBRARY;